<template>
  <div class="w-full text-center bg-rounded-white">
    <div class="loadingio-spinner-spinner-zf7id24gr0m">
      <div class="ldio-3cxwgqt8nna">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
      </div>
    </div>
  </div>
</template>

<style type="text/css">
@keyframes ldio-3cxwgqt8nna {
  0% {
    opacity: 1;
  }
  100% {
    opacity: 0;
  }
}
.ldio-3cxwgqt8nna div {
  left: 96.60000000000001px;
  top: 40.10000000000001px;
  position: absolute;
  animation: ldio-3cxwgqt8nna linear 2s infinite;
  background: #2563eb;
  width: 16.8px;
  height: 25.200000000000003px;
  border-radius: 8.4px / 12.600000000000001px;
  transform-origin: 8.4px 39.9px;
}
.ldio-3cxwgqt8nna div:nth-child(1) {
  transform: rotate(0deg);
  animation-delay: -1.6666666666666667s;
  background: #2563eb;
}
.ldio-3cxwgqt8nna div:nth-child(2) {
  transform: rotate(60deg);
  animation-delay: -1.3333333333333333s;
  background: #2563eb;
}
.ldio-3cxwgqt8nna div:nth-child(3) {
  transform: rotate(120deg);
  animation-delay: -1s;
  background: #2563eb;
}
.ldio-3cxwgqt8nna div:nth-child(4) {
  transform: rotate(180deg);
  animation-delay: -0.6666666666666666s;
  background: #2563eb;
}
.ldio-3cxwgqt8nna div:nth-child(5) {
  transform: rotate(240deg);
  animation-delay: -0.3333333333333333s;
  background: #2563eb;
}
.ldio-3cxwgqt8nna div:nth-child(6) {
  transform: rotate(300deg);
  animation-delay: 0s;
  background: #2563eb;
}
.loadingio-spinner-spinner-zf7id24gr0m {
  width: 210px;
  height: 180px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-3cxwgqt8nna {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-3cxwgqt8nna div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
